/// Persisted QR history item returned from the local database.
class QrCodeModel {
  /// Database row identifier.
  int id;

  /// Raw QR payload.
  String code;

  /// Date and time when the QR code was scanned or generated.
  DateTime scannedAt;

  /// Whether this item was generated by the app instead of scanned.
  bool isGenerated;

  /// Creates a QR history model.
  QrCodeModel({
    required this.id,
    required this.code,
    required this.scannedAt,
    required this.isGenerated,
  });

  /// Creates a history model from a database row.
  factory QrCodeModel.fromJson(Map<String, dynamic> json) {
    return QrCodeModel(
        id: json['id'] as int,
        code: json['code'] as String,
        scannedAt: DateTime.parse(json['scannedAt'] as String),
        isGenerated: (json['isGenerated']) == 1);
  }
}
