name: qr_code_scanner_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  bloc: ^8.1.4
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  qr_scanner_overlay: ^0.0.2
  share_plus: ^9.0.0
  sqflite: ^2.3.3+1
  torch_light: ^1.1.0
  url_launcher: ^6.3.0
  svg_flutter: ^0.0.1
  wifi_iot: ^0.3.19+1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gen_icons/
