/// Base class for QR history events.
sealed class HistoryEvents {}

/// Requests the full QR history list.
final class GetHistoryEvent extends HistoryEvents {}

/// Requests adding a QR code to history.
final class AddHistoryEvent extends HistoryEvents {
  /// Raw QR payload.
  final String code;

  /// Whether the QR was generated by the app.
  final bool isGenerated;

  /// Creates an event that stores [code] in history.
  AddHistoryEvent({
    required this.code,
    required this.isGenerated,
  });
}

/// Requests deletion of a QR history item.
final class DeleteHistoryEvent extends HistoryEvents {
  /// Database row identifier to delete.
  final int id;

  /// Creates a delete-history event.
  DeleteHistoryEvent({required this.id});
}
